language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  # Update Composer
  - composer self-update
  
  - mkdir tests/temp
  - mkdir tests/temp/log
  - mkdir upload
  
  # Install
  - composer install
  
script:
  - phpunit --no-globals-backup --bootstrap tests/bootstrap.php tests/AdminModule
  - phpunit --no-globals-backup --bootstrap tests/bootstrap.php tests/Entity
