language: php

php:
  - 5.4
  - 5.5

before_script:
  # Update Composer
  - composer self-update
  
  - mkdir tests/temp
  - mkdir tests/temp/log
  
  # Install
  - composer install
  
script:
  - phpunit --bootstrap tests/bootstrap.php tests
